name: Run Integration Tests

on: 
    pull_request:
        branches:
            - main
            - dev

permissions:
    contents: read
    id-token: write

jobs:
    run-postman-collection:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: Install Node
          uses: actions/setup-node@v4
          with:
            node-version: 18
        
        - name: Install Newman
          run: |
            npm install -g newman
            npm install -g newman-reporter-htmlextra
        
        - name: Run Postman Integration Tests
          run: |
            newman run ./.postman/bookmark-integration-tests.json --reporters htmlextra --verbose
        
        - name: Output test results
          uses: actions/upload-artifact@v4
          with:
            name: Reports
            path: ./newman
