name: Client UI Release

on: 
  pull_request:
    branches:
      - main
      - dev
    paths:
        - "frontendProgram/**"

jobs:
   make-release:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.x

        - name: Install ASP.NET Core
          run: dotnet tool install --global dotnet-aspnet-codegenerator

        - name: Install Maui
          run: dotnet workload install maui

        - name: Build and publish project
          run: |
            dotnet workload restore
            dotnet build -c Release "./frontendProgram/Maui Front End.csproj"
            dotnet publish -f net8.0-windows10.0.19041.0 -c Release "./frontendProgram/Maui Front End.csproj"
        

        - name: Create release
          uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            automatic_release_tag: "latest"
            prerelease: false
            title: "Windows UI release"
            files: |
              frontendProgram/bin/Release/*