name: Client UI Release

on: 
    pull_request:
        branches:
            - dev
    push:
        branches:
            - main
            - dev

permissions:
    contents: read
    id-token: write

jobs:
   make-release:
        runs-on: windows-latest

        steps:
        - uses: actions/checkout@v3

        - name: Setup dotnet
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.x

        - name: Install ASP.NET Core
          run: dotnet tool install --global dotnet-aspnet-codegenerator

        - name: Install Maui
          run: dotnet workload install maui

        - name: Build and publish project
          run: |
            dotnet restore "./frontendProgram/Maui Front End.csproj"
            dotnet build -c Release "./frontendProgram/Maui Front End.csproj"
            dotnet publish -c Release "./frontendProgram/Maui Front End.csproj"

        - name: Create release
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.ref }}
            release_name: ${{ github.ref }}
            body: |
              Extra Extra! Get your new release!
            draft: false
            prerelease: false

            